In [3]:
import numpy as np
from random import randint
from functools import reduce as r


In [4]:
def fungsim(a, b):
    M= np.random.uniform(a, b, size=(2, 2))
    return M
M=fungsim(-1, 1)
M


array([[-0.97083107, -0.53074158],
       [ 0.19774962, -0.72058988]])

In [5]:
def fungsiw(a, b):
    W= np.random.uniform(a, b, size=(3, 2))
    return W
W=fungsiw(-1, 1)
W

array([[-0.13535487,  0.10463979],
       [-0.52047653, -0.46870126],
       [-0.90920516,  0.11858907]])

In [6]:
def fungsih(a, b):
    H= np.random.uniform(a, b, size=(2, 1))
    return H
H=fungsih(-1, 1)
H

array([[-0.52051307],
       [ 0.40985099]])

In [7]:
X=[1,0,9]

In [8]:
import time

def calc_time_decorator(func):
    def inner(*args, **kwargs):
        start = time.time()
        res = func(*args, **kwargs)
        end = time.time()
        print('Time: ', end - start)
        return res
    return inner

In [9]:
import math

def aktivasi(x):
    return (math.exp(x)-math.exp(-x))/(math.exp(x)+math.exp(-x))
def WTi(W,i):
    return list(map(lambda w: w[i], W))
def WT(W):
    return list(map(lambda i: WTi(W,i), range(0,len(W[0]))))
def XW(X,W):
    return map(lambda w:r(lambda x,y:x+y, map(lambda xx,ww:xx*ww, X,w)), WT(W))
def input_to_hidden(X,W):
    return map(lambda x: aktivasi(x), XW(X,W))

A=list(input_to_hidden(X,W))

def MTi(M,i):
    return list(map(lambda m: m[i], M))
def MT(M):
    return list(map(lambda i: MTi(M,i), range(0,len(M[0]))))
def AM(A,M):
    return map(lambda m:r(lambda x,y:x+y, map(lambda aa,mm:aa*mm, A,m)), MT(M))
def hidden_to_hidden(A,M):
    return map(lambda a: a, AM(A,M))

@calc_time_decorator
def feed_forward(A,M,H):
    return hidden_to_hidden(hidden_to_hidden(A,M),H)

In [10]:
print(list(feed_forward(A,M,H)))

Time:  0.0
[-0.6163320945249138]
